name: Lighthouse CI Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: "Working Directory for the Lighthouse CI"
        required: false
        type: string
      node-version:
        description: "Node.js Version"
        required: false
        type: string
      lhci-version:
        description: "Lighthouse CI CLI Version"
        required: false
        type: string
      lighthouserc-path:
        description: "Path to lighthouserc.yml"
        required: true
        type: string
      results-summary-script:
        description: "Path to the results summary script"
        required: true
        type: string

jobs:
  lighthouse-ci:
    name: ðŸŒ„ Lighthouse CI Audit
    uses: dpbeaumont/centralized-workflows/.github/workflows/lighthouse-ci-workflow.yml@main
    with:
      working-directory: ${{ github.event.inputs.working-directory }}
      node-version: ${{ github.event.inputs.node-version }}
      lhci-version: ${{ github.event.inputs.lhci-version }}
      lighthouserc-path: ${{ github.event.inputs.lighthouserc-path }}
      results-summary-script: ${{ github.event.inputs.results-summary-script }}
